apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: andremf/pedelogo-catalogo:{{tag}}
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          resources: {}
          env:
            - name: Mongo__Host
              value: mongodb-service
            - name: Mongo__User
              value: mongodbuser
            - name: Mongo__Password
              value: mongodbpwd
            - name: Mongo__Database
              value: admin

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 8081
      targetPort: 80
  type: NodePort